# Generated by Django 4.1.7 on 2023-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, null=True)),
                ('testimony', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
